version: 2.1
orbs:
  packer: salaxander/packer@0.3
  node: circleci/node@4.1.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test
  packer-build:
    executor: packer/default
    steps:
      - checkout
      - build:
          template: base-aws-ubuntu.json
          args: '-var aws_region=eu-west-2'
workflows:
  version: 2

  build-test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - packer-build:
          requires:
          - build
