version: 2.1

orbs:
  packer: salaxander/packer@0.0.3
  node: circleci/node@4.1.0
  terraform: circleci/terraform@1.0.2
jobs:
  build-node:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test
  packer-build:
    executor: packer/default
    steps:
      - checkout
      - packer/build:
          template: base-aws-ubuntu.json
          args: -var aws_region=eu-west-1
  scale-up:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: ./iac
          backend_config: "token=${ATLAS_TOKEN}"
          context: terraform
      - terraform/apply:
          path: ./iac
          var: 'max_size=4,min_size=4'
          backend_config: "token=${ATLAS_TOKEN}"
          persist-workspace: true
          requires:
            - terraform/init
      - terraform/apply:
          path: ./iac
          backend_config: "token=${ATLAS_TOKEN}"
          attach-workspace: true
          context: terraform
          requires:
            - terraform/init
    working_directory: ~/iac
workflows:
  version: 2
  packer:
    jobs:
      - build-node:
          filters:
            branches:
              only: master
      - packer-build:
          requires:
            - build-node
      - scale-up:
          requires:
            - packer-build
