version: 2.1

orbs:
  packer: salaxander/packer@0.0.3
  node: circleci/node@4.1.0
  terraform: circleci/terraform@1.0.2
jobs:
  build-node:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test
  packer-build:
    executor: packer/default
    steps:
      - checkout
      - packer/build:
          template: base-aws-ubuntu.json
          args: -var aws_region=eu-west-1
  scale-up:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: terraform init -backend-config "token=${ATLAS_TOKEN}" ~/iac
      - run:
          command: terraform apply -var 'max_size=4' -var 'min_size=4' -auto-approve ~/iac
      - run:
          command: terraform apply -auto-approve ~/iac
workflows:
  version: 2
  packer:
    jobs:
      - build-node:
          filters:
            branches:
              only: master
      - packer-build:
          requires:
            - build-node
      - scale-up:
          requires:
            - packer-build
