version: 2.1

orbs:
  packer: salaxander/packer@0.0.3
  node: circleci/node@4.1.0
jobs:
  build-node:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test
  packer-example:
    executor: packer/default
    steps:
      - checkout
      - packer/build:
          template: base-aws-ubuntu.json
          args: -var aws_region=eu-west-1

workflows:
  version: 2
  packer:
    jobs:
      - build-node:
          filters:
            branches:
              only: master
      - packer-example:
          requires:
            - build-node
